### ISSUE TITLE
As Municipality of Bolzano I would like that the parking application has a better presentation of the real-time data visualized in the list component

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/parking-app#10]
- [x] include timestamp related to the real-time value
- [x] more visibility to the real-time value (in direction of the previous parking APP: just a number, with color depending on the free parking lots - grey if not real-time data; no map background

Live on testing https://parking.opendatahub.testingmachine.eu/

![Screenshot from 2023-06-08 22-41-26](https://github.com/noi-techpark/parking-app/assets/9825179/a203baa5-3abe-4bd8-a7e0-3c1d1b32619f)

**Comment by dulvui** [comment]
I implemented now the timestamp and better availability visibility. I saw that the performance seems also much better, because the little maps where quite heavy.
https://parking.opendatahub.testingmachine.eu/

**Comment by rcavaliere** [comment]
@dulvui looks very good, I like it! Just one comment: for the on-street parking sensors, I would not display each single sensor, but the total related to the group they belong (smetadata -> group). Each block should therefore characterize the group of sensors. On the map we can display each single sensor, maybe in the tooltip we can think to add the sensor name.

**Comment by dulvui** [comment]
@rcavaliere Great! Now the Parking Sensors are grouped in the list. It was not so trivial as I thought, but now I refactored the code a lot and I solved also other issues, like the parking sensors where mapped wrong like once happened on the open trip planner.
https://parking.opendatahub.testingmachine.eu/

**Comment by rcavaliere** [comment]
@dulvui great! One thing: we have also on-street parking data by systems. I think that at present they are not visualized, they also cover e.g. Bressanone. Can we easily manage to display this data as well?

**Comment by dulvui** [comment]
@rcavaliere I checked now and they parking sensors of Bressanone are not shown because they are not active.
I checked now the data collector and he sets the stations to inactive, if no data arrives for more than 7 days.
I could show inactive stations in gray or is there a problem with the data collector, since we don't receive data from Bressanone since  3/2/2023?

**Comment by rcavaliere** [comment]
@dulvui really? I didn't find this in Grafana, are we monitoring this? No, don't put inactive stations visible, let's fix this issue

**Comment by dulvui** [comment]
@rcavaliere The stations doesn't show up in Grafana, because it is set to inactive and technically, it is correct, that an inactive station doesn't receive data. The dashboards all filter out stations that have active = false.
I simply found the station on analytics.opendatahub.com where also inactive stations are shown.

**Comment by rcavaliere** [comment]
But can you check if the web-service is active or if they are simply pushing an empty list of stations?

**Comment by dulvui** [comment]
@rcavaliere The datacollector still gets data from 4 Parking Sensors in Bolzano:
https://mobility.api.opendatahub.com/v2/flat/ParkingStation%2CParkingSensor/?limit=-1&distinct=true&where=and(sorigin.eq.systems,sactive.eq.true)
But the Parking Sensors of Merano and Bressanone don't send data since a few months:
https://mobility.api.opendatahub.com/v2/flat/ParkingStation%2CParkingSensor/?limit=-1&distinct=true&where=and(sorigin.eq.systems,sactive.eq.false)

The data collector works with MQTT, so there is no data list provided by the data provider. He simply gets all stations from the Open Data Hub and then sets a station to inactive, if the last measurement is older than 7 days.
I could increment this date or disable this "synchronization" of the stations, so we can see easier if data is not coming.

**Comment by rcavaliere** [comment]
@dulvui yes, try to make some additional test please. Should we see on that view this kind of issue? https://grafana.testingmachine.eu/d/NQ9asNaVk/missing-data-by-station?from=now-6M&to=now&orgId=1

**Comment by dulvui** [comment]
@rcavaliere Yes exactly, in this dashboard then it should be visible.
I could also remove the active filter from the query this dashboard does and add it to the columns, so inactive stations can be filtered out manually afterwards.

**Comment by dulvui** [comment]
I added now the active column in the dashboard. Now if you set there the filter to active = false and then stationtype = ParkingSensor the missing stations are visible

**Comment by rcavaliere** [comment]
For me the improvements are fine. I will ask also the Municipality of BZ to give feedback
