### ISSUE TITLE
As a parking APP user I would like to have a clustering of the icons on the map when I make zoom out

### ISSUE THREAD

**Issue by rcavaliere** [noi-techpark/parking-app#8]

**Comment by dulvui** [comment]
@rcavaliere clustering is now life in testing. There is still a problem with the zooming when clicking on a cluster. Instead of zooming towards the cluster, it just increments the zoom level. I found the cause of the problem but still not the solution. I will try to fix that too.
Now we just need to define colors and size of clusters. 
https://parking.opendatahub.testingmachine.eu/

**Comment by dulvui** [comment]
done and released on production
